### ISSUE TITLE
Implement Linked List Operations for Memory Blocks

### ISSUE THREAD

**Issue by yogimathius** [rswhipple/jsmalloc#11]
## Description

Implement linked list operations for managing memory blocks within heaps.

## Tasks
- [ ] Implement the function to add memory blocks to the linked list within a heap (`add_block`).
- [ ] Implement the function to remove memory blocks from the linked list within a heap (`remove_block`).
- [ ] Implement the function to traverse the linked list of memory blocks within a heap (`traverse_blocks` or `find_free`?).

## Success Criteria
- Linked list operations function correctly, allowing efficient organization and management of memory blocks within heaps.

**Comment by yogimathius** [comment]
closing as this is duplicate work and these functions can just be captured as part of each memory allocation function's work
