### ISSUE TITLE
Handle large allocation sizes

### ISSUE THREAD

**Issue by yogimathius** [rswhipple/jsmalloc#15]
### Description

Our current implementation is setup to handle only small and medium allocation sizes. Based on the way we are structuring the programs, we intend to allocate larger sizes on a more custom level which still needs to be investigated and implemented.

### Tasks

- [ ] Align on approach for handling large allocation sizes
- [ ] Implement logic designed to allocate large memory chunks
- [ ] Update allocation functions to handle this edge case
